#!/usr/bin/env python3
"""Emit NASM data tables of SHA-256 / HMAC / HKDF test vectors.

The expected outputs are computed here with Python's hashlib/hmac, which
are the authoritative reference; the linnea selftest binary compares its
own assembly output against these tables. Inputs are the canonical RFC /
NIST cases plus a spread of sizes that exercise the block boundary and
the incremental buffering path. Run: python3 gen_vectors.py > sha256_vectors.inc
"""
import hashlib
import hmac


def hkdf_extract(salt, ikm):
    return hmac.new(salt, ikm, hashlib.sha256).digest()


def hkdf_expand(prk, info, length):
    out, t, i = b"", b"", 1
    while len(out) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        out += t
        i += 1
    return out[:length]


# --- X25519 reference (RFC 7748), for generating and cross-checking ------
_P = 2 ** 255 - 19


def _decode_le(b):
    return sum(b[i] << (8 * i) for i in range(len(b)))


def _decode_u(u):
    u = bytearray(u)
    u[31] &= 0x7f
    return _decode_le(u)


def _decode_scalar(k):
    k = bytearray(k)
    k[0] &= 248
    k[31] &= 127
    k[31] |= 64
    return _decode_le(k)


def _encode_u(x):
    return bytes([(x >> (8 * i)) & 0xff for i in range(32)])


def x25519(k_bytes, u_bytes):
    k = _decode_scalar(k_bytes)
    u = _decode_u(u_bytes)
    x1, x2, z2, x3, z3, swap = u, 1, 0, u, 1, 0
    for t in reversed(range(255)):
        kt = (k >> t) & 1
        swap ^= kt
        if swap:
            x2, x3 = x3, x2
            z2, z3 = z3, z2
        swap = kt
        a = (x2 + z2) % _P
        aa = a * a % _P
        b = (x2 - z2) % _P
        bb = b * b % _P
        e = (aa - bb) % _P
        c = (x3 + z3) % _P
        d = (x3 - z3) % _P
        da = d * a % _P
        cb = c * b % _P
        x3 = (da + cb) ** 2 % _P
        z3 = x1 * (da - cb) ** 2 % _P
        x2 = aa * bb % _P
        z2 = e * (aa + 121665 * e) % _P
    if swap:
        x2, x3 = x3, x2
        z2, z3 = z3, z2
    return _encode_u(x2 * pow(z2, _P - 2, _P) % _P)


def x25519_iter(n):
    k = bytes([9] + [0] * 31)
    u = k
    for _ in range(n):
        r = x25519(k, u)
        u = k
        k = r
    return k


def blob(label, data):
    """One db line naming a byte string; empty strings still get a label."""
    if not data:
        return "%s: db 0   ; (empty)\n" % label   # a valid address; len 0
    body = ", ".join(str(b) for b in data)
    return "%s: db %s\n" % (label, body)


def main():
    out = []
    out.append("; Generated by test/crypto/gen_vectors.py — do not edit.\n")
    out.append("section .rodata\n")

    # ---- SHA-256: messages of assorted lengths ----------------------
    sha_msgs = [
        b"",
        b"abc",
        b"The quick brown fox jumps over the lazy dog",
        b"a" * 55,     # the largest that still fits one padded block
        b"a" * 56,     # forces a second, length-only block
        b"a" * 63,
        b"a" * 64,     # exactly one block
        b"a" * 65,     # one block plus a byte
        b"a" * 127,
        b"a" * 128,
        bytes(range(256)) * 4,   # 1024 bytes, several blocks
    ]
    labels = []
    for n, m in enumerate(sha_msgs):
        out.append(blob("sha_msg_%d" % n, m))
        out.append(blob("sha_exp_%d" % n, hashlib.sha256(m).digest()))
        labels.append((n, len(m)))
    out.append("align 8\nsha256_tests:\n")
    for n, ln in labels:
        out.append("    dq sha_msg_%d, %d, sha_exp_%d\n" % (n, ln, n))
    out.append("sha256_test_count equ (($ - sha256_tests) / 24)\n")

    # ---- HMAC-SHA256: RFC 4231 test cases 1-7 -----------------------
    hmac_cases = [
        (b"\x0b" * 20, b"Hi There"),
        (b"Jefe", b"what do ya want for nothing?"),
        (b"\xaa" * 20, b"\xdd" * 50),
        (bytes(range(1, 26)), b"\xcd" * 50),
        (b"\xaa" * 131, b"Test Using Larger Than Block-Size Key - Hash Key First"),
        (b"\xaa" * 131,
         b"This is a test using a larger than block-size key and a larger "
         b"than block-size data. The key needs to be hashed before being "
         b"used by the HMAC algorithm."),
    ]
    labels = []
    for n, (k, m) in enumerate(hmac_cases):
        out.append(blob("hmac_key_%d" % n, k))
        out.append(blob("hmac_msg_%d" % n, m))
        out.append(blob("hmac_exp_%d" % n,
                        hmac.new(k, m, hashlib.sha256).digest()))
        labels.append((n, len(k), len(m)))
    out.append("align 8\nhmac_tests:\n")
    for n, kl, ml in labels:
        out.append("    dq hmac_key_%d, %d, hmac_msg_%d, %d, hmac_exp_%d\n"
                    % (n, kl, n, ml, n))
    out.append("hmac_test_count equ (($ - hmac_tests) / 40)\n")

    # ---- HKDF-Extract: RFC 5869 cases 1-3 ---------------------------
    ext_cases = [
        (b"\x00" * 13, b"\x0b" * 22),                       # salt, IKM
        (bytes(range(0x00, 0x50)), bytes(range(0x00, 0x22))),
        (b"", b"\x0b" * 22),                                # empty salt
    ]
    labels = []
    for n, (salt, ikm) in enumerate(ext_cases):
        out.append(blob("ext_salt_%d" % n, salt))
        out.append(blob("ext_ikm_%d" % n, ikm))
        out.append(blob("ext_exp_%d" % n, hkdf_extract(salt, ikm)))
        labels.append((n, len(salt), len(ikm)))
    out.append("align 8\nhkdf_extract_tests:\n")
    for n, sl, il in labels:
        out.append("    dq ext_salt_%d, %d, ext_ikm_%d, %d, ext_exp_%d\n"
                    % (n, sl, n, il, n))
    out.append("hkdf_extract_test_count equ (($ - hkdf_extract_tests) / 40)\n")

    # ---- HKDF-Expand: RFC 5869 cases 1-3 plus a short one -----------
    prk1 = hkdf_extract(b"\x00" * 13, b"\x0b" * 22)
    prk2 = hkdf_extract(bytes(range(0x00, 0x50)), bytes(range(0x00, 0x22)))
    prk3 = hkdf_extract(b"", b"\x0b" * 22)
    exp_cases = [
        (prk1, bytes(range(0xf0, 0xfa)), 42),
        (prk2, bytes(range(0xb0, 0x100)), 82),   # crosses several T blocks
        (prk3, b"", 42),
        (prk1, b"", 1),                          # a single byte of output
        (prk1, b"tls13 label context", 32),      # one exact block
    ]
    labels = []
    for n, (prk, info, ln) in enumerate(exp_cases):
        out.append(blob("exp_prk_%d" % n, prk))
        out.append(blob("exp_info_%d" % n, info))
        out.append(blob("exp_out_%d" % n, hkdf_expand(prk, info, ln)))
        labels.append((n, len(prk), len(info), ln))
    out.append("align 8\nhkdf_expand_tests:\n")
    for n, pl, il, ol in labels:
        out.append("    dq exp_prk_%d, %d, exp_info_%d, %d, exp_out_%d, %d\n"
                    % (n, pl, n, il, n, ol))
    out.append("hkdf_expand_test_count equ (($ - hkdf_expand_tests) / 48)\n")

    # ---- X25519: RFC 7748 section 5.2 single-shot vectors ------------
    x_cases = [
        (bytes.fromhex("a546e36bf0527c9d3b16154b82465edd"
                       "62144c0ac1fc5a18506a2244ba449ac4"),
         bytes.fromhex("e6db6867583030db3594c1a424b15f7c"
                       "726624ec26b3353b10a903a6d0ab1c4c")),
        (bytes.fromhex("4b66e9d4d1b4673c5ad22691957d6af5"
                       "c11b6421e0ea01d42ca4169e7918ba0d"),
         bytes.fromhex("e5210f12786811d3f4b7959d0538ae2c"
                       "31dbe7106fc03c3efc4cd549c715a493")),
    ]
    # RFC 7748's published answers, to fail loudly if the reference drifts.
    expect = [
        "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552",
        "95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957",
    ]
    # Adversarial u-coordinates random pairs never hit: low-order points
    # (which must yield an all-zero shared secret), the 0 and 1 points,
    # and non-canonical encodings at and above p. Expected values come
    # from the reference; the point is that the assembly agrees on them.
    fixed_scalar = bytes.fromhex(
        "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
    edge_u = [
        bytes(32),                                  # 0
        bytes([1]) + bytes(31),                     # 1
        # canonical low-order points of the curve (order 1, 2, 4, 8)
        bytes.fromhex("e0eb7a7c3b41b8ae1656e3faf19fc46ada098deb9c32b1fd"
                      "866205165f49b800"),
        bytes.fromhex("5f9c95bca3508c24b1d0b1559c83ef5b04445cc4581c8e86"
                      "d8224eddd09f1157"),
        bytes(b"\xff" * 32),                        # non-canonical, > p
        bytes.fromhex("ecffffffffffffffffffffffffffffffffffffffffffffff"
                      "ffffffffffffff7f"),          # p - 1
        bytes.fromhex("edffffffffffffffffffffffffffffffffffffffffffffff"
                      "ffffffffffffff7f"),          # p
    ]
    for u in edge_u:
        x_cases.append((fixed_scalar, u))

    labels = []
    for n, (scalar, u) in enumerate(x_cases):
        got = x25519(scalar, u)
        if n < len(expect):
            assert got.hex() == expect[n], (got.hex(), expect[n])
        out.append(blob("x_scalar_%d" % n, scalar))
        out.append(blob("x_u_%d" % n, u))
        out.append(blob("x_exp_%d" % n, got))
        labels.append(n)
    out.append("align 8\nx25519_tests:\n")
    for n in labels:
        out.append("    dq x_scalar_%d, x_u_%d, x_exp_%d\n" % (n, n, n))
    out.append("x25519_test_count equ (($ - x25519_tests) / 24)\n")

    # ---- X25519 iterated: the RFC's k=u=9 recurrence ----------------
    # 1 and 1000 rounds are in-suite; the million-round check runs in the
    # dev harness (test/crypto/diff_x25519.py).
    iters = [
        (1, "422c8e7a6227d7bca1350b3e2bb7279f7897b87bb6854b783c60e80311ae3079"),
        (1000, "684cf59ba83309552800ef566f2f4d3c1c3887c49360e3875f2eb94d99532c51"),
    ]
    labels = []
    for n, (rounds, exp) in enumerate(iters):
        got = x25519_iter(rounds)
        assert got.hex() == exp, (got.hex(), exp)
        out.append(blob("x_iter_exp_%d" % n, got))
        labels.append((n, rounds))
    out.append("align 8\nx25519_iter_tests:\n")
    for n, rounds in labels:
        out.append("    dq %d, x_iter_exp_%d\n" % (rounds, n))
    out.append("x25519_iter_test_count equ (($ - x25519_iter_tests) / 16)\n")

    print("".join(out), end="")


if __name__ == "__main__":
    main()
