#!/usr/bin/env python3
"""Emit NASM data tables of SHA-256 / HMAC / HKDF test vectors.

The expected outputs are computed here with Python's hashlib/hmac, which
are the authoritative reference; the linnea selftest binary compares its
own assembly output against these tables. Inputs are the canonical RFC /
NIST cases plus a spread of sizes that exercise the block boundary and
the incremental buffering path. Run: python3 gen_vectors.py > sha256_vectors.inc
"""
import hashlib
import hmac


def hkdf_extract(salt, ikm):
    return hmac.new(salt, ikm, hashlib.sha256).digest()


def hkdf_expand(prk, info, length):
    out, t, i = b"", b"", 1
    while len(out) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        out += t
        i += 1
    return out[:length]


def blob(label, data):
    """One db line naming a byte string; empty strings still get a label."""
    if not data:
        return "%s: db 0   ; (empty)\n" % label   # a valid address; len 0
    body = ", ".join(str(b) for b in data)
    return "%s: db %s\n" % (label, body)


def main():
    out = []
    out.append("; Generated by test/crypto/gen_vectors.py — do not edit.\n")
    out.append("section .rodata\n")

    # ---- SHA-256: messages of assorted lengths ----------------------
    sha_msgs = [
        b"",
        b"abc",
        b"The quick brown fox jumps over the lazy dog",
        b"a" * 55,     # the largest that still fits one padded block
        b"a" * 56,     # forces a second, length-only block
        b"a" * 63,
        b"a" * 64,     # exactly one block
        b"a" * 65,     # one block plus a byte
        b"a" * 127,
        b"a" * 128,
        bytes(range(256)) * 4,   # 1024 bytes, several blocks
    ]
    labels = []
    for n, m in enumerate(sha_msgs):
        out.append(blob("sha_msg_%d" % n, m))
        out.append(blob("sha_exp_%d" % n, hashlib.sha256(m).digest()))
        labels.append((n, len(m)))
    out.append("align 8\nsha256_tests:\n")
    for n, ln in labels:
        out.append("    dq sha_msg_%d, %d, sha_exp_%d\n" % (n, ln, n))
    out.append("sha256_test_count equ (($ - sha256_tests) / 24)\n")

    # ---- HMAC-SHA256: RFC 4231 test cases 1-7 -----------------------
    hmac_cases = [
        (b"\x0b" * 20, b"Hi There"),
        (b"Jefe", b"what do ya want for nothing?"),
        (b"\xaa" * 20, b"\xdd" * 50),
        (bytes(range(1, 26)), b"\xcd" * 50),
        (b"\xaa" * 131, b"Test Using Larger Than Block-Size Key - Hash Key First"),
        (b"\xaa" * 131,
         b"This is a test using a larger than block-size key and a larger "
         b"than block-size data. The key needs to be hashed before being "
         b"used by the HMAC algorithm."),
    ]
    labels = []
    for n, (k, m) in enumerate(hmac_cases):
        out.append(blob("hmac_key_%d" % n, k))
        out.append(blob("hmac_msg_%d" % n, m))
        out.append(blob("hmac_exp_%d" % n,
                        hmac.new(k, m, hashlib.sha256).digest()))
        labels.append((n, len(k), len(m)))
    out.append("align 8\nhmac_tests:\n")
    for n, kl, ml in labels:
        out.append("    dq hmac_key_%d, %d, hmac_msg_%d, %d, hmac_exp_%d\n"
                    % (n, kl, n, ml, n))
    out.append("hmac_test_count equ (($ - hmac_tests) / 40)\n")

    # ---- HKDF-Extract: RFC 5869 cases 1-3 ---------------------------
    ext_cases = [
        (b"\x00" * 13, b"\x0b" * 22),                       # salt, IKM
        (bytes(range(0x00, 0x50)), bytes(range(0x00, 0x22))),
        (b"", b"\x0b" * 22),                                # empty salt
    ]
    labels = []
    for n, (salt, ikm) in enumerate(ext_cases):
        out.append(blob("ext_salt_%d" % n, salt))
        out.append(blob("ext_ikm_%d" % n, ikm))
        out.append(blob("ext_exp_%d" % n, hkdf_extract(salt, ikm)))
        labels.append((n, len(salt), len(ikm)))
    out.append("align 8\nhkdf_extract_tests:\n")
    for n, sl, il in labels:
        out.append("    dq ext_salt_%d, %d, ext_ikm_%d, %d, ext_exp_%d\n"
                    % (n, sl, n, il, n))
    out.append("hkdf_extract_test_count equ (($ - hkdf_extract_tests) / 40)\n")

    # ---- HKDF-Expand: RFC 5869 cases 1-3 plus a short one -----------
    prk1 = hkdf_extract(b"\x00" * 13, b"\x0b" * 22)
    prk2 = hkdf_extract(bytes(range(0x00, 0x50)), bytes(range(0x00, 0x22)))
    prk3 = hkdf_extract(b"", b"\x0b" * 22)
    exp_cases = [
        (prk1, bytes(range(0xf0, 0xfa)), 42),
        (prk2, bytes(range(0xb0, 0x100)), 82),   # crosses several T blocks
        (prk3, b"", 42),
        (prk1, b"", 1),                          # a single byte of output
        (prk1, b"tls13 label context", 32),      # one exact block
    ]
    labels = []
    for n, (prk, info, ln) in enumerate(exp_cases):
        out.append(blob("exp_prk_%d" % n, prk))
        out.append(blob("exp_info_%d" % n, info))
        out.append(blob("exp_out_%d" % n, hkdf_expand(prk, info, ln)))
        labels.append((n, len(prk), len(info), ln))
    out.append("align 8\nhkdf_expand_tests:\n")
    for n, pl, il, ol in labels:
        out.append("    dq exp_prk_%d, %d, exp_info_%d, %d, exp_out_%d, %d\n"
                    % (n, pl, n, il, n, ol))
    out.append("hkdf_expand_test_count equ (($ - hkdf_expand_tests) / 48)\n")

    print("".join(out), end="")


if __name__ == "__main__":
    main()
