#!/usr/bin/env python3
# Emit test/quic/quic_vectors.inc from RFC 9001 Appendix A.2: the protected
# client Initial packet and the expected unprotected payload prefix.
import re, sys
txt = open(sys.argv[1]).read()

# The protected packet: the hex block after "The resulting protected packet is:"
m = txt.split("The resulting protected packet is:", 1)[1]
# take lines until the next section header (A.3)
block = m.split("A.3", 1)[0]
hexstr = "".join(re.findall(r'\b[0-9a-f ]{2,}\b', block))
hexstr = re.sub(r'[^0-9a-f]', '', block)
pkt = bytes.fromhex(hexstr)
# sanity: starts with c00000..., a ~1200-byte packet
assert pkt[:6] == bytes.fromhex("c000000001"+"08"), pkt[:8].hex()

# expected unprotected payload prefix (the CRYPTO frame + start of ClientHello)
# from A.2: 060040f1010000ed0303ebf8fa5...
prefix = bytes.fromhex("060040f1010000ed0303ebf8fa56f129"
                       "39b9584a3896472ec40bb863cfd3e868")

def emit(name, b):
    out = [f"{name}:"]
    for i in range(0, len(b), 16):
        out.append("    db " + ", ".join("0x%02x" % c for c in b[i:i+16]))
    return "\n".join(out)

print("; Generated by tools/gen_quic_vectors.py from RFC 9001 Appendix A.2.")
print("; The protected client Initial packet and its unprotected payload prefix.")
print()
print(emit("quic_a2_packet", pkt))
print(f"quic_a2_packet_len equ {len(pkt)}")
print()
print(emit("quic_a2_dcid", bytes.fromhex("8394c8f03e515708")))
print()
print(emit("quic_a2_plain_prefix", prefix))
print(f"quic_a2_plain_prefix_len equ {len(prefix)}")
