#!/usr/bin/env python3
# Generate include/linnea_hpack_data.inc from RFC 7541 (HPACK): the 61-entry
# static table (Appendix A) and the canonical Huffman decode tables
# (Appendix B). Run once; the .inc is committed. Not part of the build.
#
#   python3 tools/gen_hpack_tables.py rfc7541.txt > include/linnea_hpack_data.inc
#
# Fetch the source with:
#   curl -s https://www.rfc-editor.org/rfc/rfc7541.txt -o rfc7541.txt
import re, sys

txt = open(sys.argv[1]).read().splitlines()

# --- Appendix A: static table (index -> name, value) --------------------
STATIC = []  # (name, value) for indices 1..61
in_a = False
row = re.compile(r'^\s*\|\s*(\d+)\s*\|\s*(\S[^|]*?)\s*\|\s*([^|]*?)\s*\|\s*$')
for ln in txt:
    if 'Static Table Entries' in ln:
        break
    if ln.strip().startswith('| Index'):
        in_a = True
        continue
    if in_a:
        m = row.match(ln)
        if m:
            idx, name, val = int(m.group(1)), m.group(2), m.group(3)
            assert idx == len(STATIC) + 1, (idx, name)
            STATIC.append((name, val))
assert len(STATIC) == 61, len(STATIC)

# --- Appendix B: Huffman (sym -> hexcode, bitlen) -----------------------
HUFF = []  # index = symbol 0..256; (code, bits)
hb = re.compile(r'\(\s*(\d+)\)\s+\|.*?\s([0-9a-f]+)\s+\[\s*(\d+)\]\s*$')
in_b = False
for ln in txt:
    if ln.startswith('Appendix B'):
        in_b = True
        continue
    if not in_b:
        continue
    m = hb.search(ln)
    if m:
        sym, code, bits = int(m.group(1)), int(m.group(2), 16), int(m.group(3))
        assert sym == len(HUFF), (sym, len(HUFF))
        HUFF.append((code, bits))
assert len(HUFF) == 257, len(HUFF)          # 0..255 + EOS(256)
assert HUFF[256] == (0x3fffffff, 30)        # EOS

# Canonical decode tables, indexed by code length 1..30.
MAXLEN = 30
order = sorted(range(257), key=lambda s: (HUFF[s][1], HUFF[s][0]))
cnt = [0] * (MAXLEN + 1)
first_code = [0] * (MAXLEN + 1)
first_sym = [0] * (MAXLEN + 1)
syms = []
i = 0
for length in range(1, MAXLEN + 1):
    group = [s for s in order if HUFF[s][1] == length]
    cnt[length] = len(group)
    first_sym[length] = i
    if group:
        first_code[length] = HUFF[group[0]][0]
        # canonical: consecutive codes, ascending symbol order
        for k, s in enumerate(group):
            assert HUFF[s][0] == first_code[length] + k, (length, s)
        syms.extend(group)
        i += len(group)
    else:
        first_code[length] = 0
# canonical continuity check
prev = 0
for length in range(1, MAXLEN + 1):
    if cnt[length]:
        assert first_code[length] == prev, (length, first_code[length], prev)
    prev = (prev + cnt[length]) << 1

# --- emit NASM ----------------------------------------------------------
out = []
w = out.append
w("; Generated by tools/gen_hpack_tables.py from RFC 7541 — do not edit.")
w("; HPACK static table (Appendix A) and canonical Huffman decode tables")
w("; (Appendix B). Included by src/linnea_hpack.asm.")
w("")
w("HPACK_STATIC_COUNT equ 61")
w("HPACK_HUFF_MAXLEN  equ 30")
w("")
w("section .rodata")
w("")

# static-table strings blob + descriptor array
w("; static entries: name/value strings, referenced by hpack_static_tab")
blob = bytearray()
offs = []
def intern(s):
    b = s.encode()
    off = len(blob)
    blob.extend(b)
    return off, len(b)
descs = []
for name, val in STATIC:
    no, nl = intern(name)
    vo, vl = intern(val)
    descs.append((no, nl, vo, vl))

w("hpack_static_blob:")
# emit blob as db lines of printable text where possible
def db_line(bs):
    parts, run = [], []
    def flush():
        if run:
            parts.append('"' + ''.join(run) + '"')
            run.clear()
    for c in bs:
        if 32 <= c < 127 and c not in (34,):
            run.append(chr(c))
        else:
            flush(); parts.append(str(c))
    flush()
    return ', '.join(parts) if parts else '0'
# chunk blob into readable lines
for j in range(0, len(blob), 32):
    w("    db " + db_line(blob[j:j+32]))
w("")
w("; hpack_static_tab[i] = {name_off, name_len, val_off, val_len} (dwords),")
w("; i = static index - 1. Offsets are into hpack_static_blob.")
w("hpack_static_tab:")
for (no, nl, vo, vl) in descs:
    w(f"    dd {no}, {nl}, {vo}, {vl}")
w("HPACK_STATIC_ENTRY_SIZE equ 16")
w("")

# Huffman tables
w("; Huffman: per-length canonical decode. Index 0 unused; 1..30 valid.")
w("hpack_huff_cnt:        dd " + ", ".join(str(cnt[l]) for l in range(0, MAXLEN + 1)))
w("hpack_huff_first_code: dd " + ", ".join(str(first_code[l]) for l in range(0, MAXLEN + 1)))
w("hpack_huff_first_sym:  dd " + ", ".join(str(first_sym[l]) for l in range(0, MAXLEN + 1)))
w("; symbols in canonical (len, code) order; values 0..256 (256 = EOS)")
w("hpack_huff_syms:")
for j in range(0, len(syms), 16):
    w("    dw " + ", ".join(str(s) for s in syms[j:j+16]))
w(f"HPACK_HUFF_SYM_COUNT equ {len(syms)}")
w("HPACK_HUFF_EOS equ 256")
w("")

sys.stdout.write("\n".join(out) + "\n")
