#!/usr/bin/env python3
# Emit test/quic/quic_hs_vectors.inc: fixed ECDHE inputs and the expected QUIC
# handshake packet keys, computed independently with the `cryptography` library
# as a reference for linnea_quic_hs_secrets (TLS 1.3 key schedule + QUIC keys).
import hashlib
import hmac as _hmac
import sys

from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey, X25519PublicKey)
from cryptography.hazmat.primitives.kdf.hkdf import HKDFExpand
from cryptography.hazmat.primitives import hashes


def hkdf_extract(salt, ikm):
    if not salt:
        salt = b"\x00" * 32
    return _hmac.new(salt, ikm, hashlib.sha256).digest()


def hkdf_expand_label(secret, label, context, length):
    full = b"tls13 " + label
    info = (length.to_bytes(2, "big") + bytes([len(full)]) + full
            + bytes([len(context)]) + context)
    return HKDFExpand(hashes.SHA256(), length, info).derive(secret)


def derive_secret(secret, label, ctx_hash):
    return hkdf_expand_label(secret, label, ctx_hash, 32)


def quic_keys(secret):
    return (hkdf_expand_label(secret, b"quic key", b"", 16)
            + hkdf_expand_label(secret, b"quic iv", b"", 12)
            + hkdf_expand_label(secret, b"quic hp", b"", 16))


# Fixed, arbitrary inputs (reproducible).
client_priv = bytes(range(1, 33))
server_priv = bytes(range(33, 65))
th = hashlib.sha256(b"CH||SH transcript").digest()      # a stand-in H(CH..SH)

client_pub = X25519PrivateKey.from_private_bytes(client_priv).public_key() \
    .public_bytes_raw()
shared = X25519PrivateKey.from_private_bytes(server_priv).exchange(
    X25519PublicKey.from_public_bytes(client_pub))

early = hkdf_extract(b"", b"\x00" * 32)
derived = derive_secret(early, b"derived", hashlib.sha256(b"").digest())
hs = hkdf_extract(derived, shared)
c_hs = derive_secret(hs, b"c hs traffic", th)
s_hs = derive_secret(hs, b"s hs traffic", th)
client_keys = quic_keys(c_hs)     # key(16) iv(12) hp(16) = 44 bytes
server_keys = quic_keys(s_hs)


def emit(name, b):
    out = [f"{name}:"]
    for i in range(0, len(b), 16):
        out.append("    db " + ", ".join("0x%02x" % c for c in b[i:i + 16]))
    return "\n".join(out)


print("; Generated by tools/gen_quic_hs_vectors.py (cryptography as reference).")
print("; Fixed ECDHE inputs and the expected QUIC handshake packet keys.")
print()
print(emit("qhs_client_pub", client_pub))
print(emit("qhs_server_priv", server_priv))
print(emit("qhs_th", th))
print(emit("qhs_exp_client", client_keys))
print(emit("qhs_exp_server", server_keys))
