#!/usr/bin/env python3
# Generate include/linnea_qpack_data.inc from RFC 9204 Appendix A: the 99-entry
# QPACK static table. QPACK reuses HPACK's Huffman code (RFC 7541 Appendix B),
# so only the static table is emitted here — the Huffman decode tables live in
# include/linnea_hpack_data.inc and are shared. Run once; the .inc is committed.
#
#   python3 tools/gen_qpack_tables.py rfc9204.txt > include/linnea_qpack_data.inc
#
# Fetch the source with:
#   curl -s https://www.rfc-editor.org/rfc/rfc9204.txt -o rfc9204.txt
import re
import sys

txt = open(sys.argv[1]).read().splitlines()

# Appendix A rows: | index | name | value | . Restrict to the table region so
# the field-line example dumps later in the document cannot be misread as rows.
start = max(i for i, ln in enumerate(txt) if ln.strip() == "Appendix A.  Static Table")
row = re.compile(r'^\s*\|\s*(\d+)\s*\|\s*(\S[^|]*?)\s*\|\s*([^|]*?)\s*\|\s*$')
STATIC = {}
for ln in txt[start:]:
    m = row.match(ln)
    if m:
        idx = int(m.group(1))
        if 0 <= idx <= 98 and idx not in STATIC:
            STATIC[idx] = (m.group(2).strip(), m.group(3).strip())
assert len(STATIC) == 99, len(STATIC)
entries = [STATIC[i] for i in range(99)]

# Intern each distinct string once into a single blob.
blob = bytearray()
offs = {}


def intern(s):
    b = s.encode()
    if b not in offs:
        offs[b] = len(blob)
        blob.extend(b)
    return offs[b]


tab = []
for name, val in entries:
    no = intern(name)
    vo = intern(val)
    tab.append((no, len(name), vo, len(val)))


def emit_blob(name, b):
    print(f"{name}:")
    for i in range(0, len(b), 16):
        chunk = b[i:i + 16]
        print("    db " + ", ".join("0x%02x" % c for c in chunk))


print("; Generated by tools/gen_qpack_tables.py from RFC 9204 Appendix A — do")
print("; not edit. QPACK static table (99 entries). Huffman tables are shared")
print("; from linnea_hpack_data.inc. Included by src/linnea_qpack.asm.")
print()
print("QPACK_STATIC_COUNT equ 99")
print()
print("section .rodata")
print()
print("; distinct name/value strings, referenced by qpack_static_tab")
emit_blob("qpack_static_blob", blob)
print()
print("; qpack_static_tab[i] = {name_off, name_len, val_off, val_len} (dwords),")
print("; i = static index (0-based). Offsets are into qpack_static_blob.")
print("qpack_static_tab:")
for (no, nl, vo, vl) in tab:
    print(f"    dd {no}, {nl}, {vo}, {vl}")
