#!/usr/bin/env python3
# Emit test/quic/quic_vectors.inc from RFC 9001 Appendix A.2: the protected
# client Initial packet and the expected unprotected payload prefix.
import re, sys
txt = open(sys.argv[1]).read()

# The protected packet: the hex block after "The resulting protected packet is:"
m = txt.split("The resulting protected packet is:", 1)[1]
# take lines until the next section header (A.3)
block = m.split("A.3", 1)[0]
hexstr = "".join(re.findall(r'\b[0-9a-f ]{2,}\b', block))
hexstr = re.sub(r'[^0-9a-f]', '', block)
pkt = bytes.fromhex(hexstr)
# sanity: starts with c00000..., a ~1200-byte packet
assert pkt[:6] == bytes.fromhex("c000000001"+"08"), pkt[:8].hex()

# expected unprotected payload prefix (the CRYPTO frame + start of ClientHello)
# from A.2: 060040f1010000ed0303ebf8fa5...
prefix = bytes.fromhex("060040f1010000ed0303ebf8fa56f129"
                       "39b9584a3896472ec40bb863cfd3e868")

def emit(name, b):
    out = [f"{name}:"]
    for i in range(0, len(b), 16):
        out.append("    db " + ", ".join("0x%02x" % c for c in b[i:i+16]))
    return "\n".join(out)

print("; Generated by tools/gen_quic_vectors.py from RFC 9001 Appendix A.2.")
print("; The protected client Initial packet and its unprotected payload prefix.")
print()
print(emit("quic_a2_packet", pkt))
print(f"quic_a2_packet_len equ {len(pkt)}")
print()
print(emit("quic_a2_dcid", bytes.fromhex("8394c8f03e515708")))
print()
print(emit("quic_a2_plain_prefix", prefix))
print(f"quic_a2_plain_prefix_len equ {len(prefix)}")
print()

# --- A.3 Server Initial: the send-side (packet protection) vector. ---
# Anchor on phrases unique to the A.3 body (the section header also appears
# in the table of contents, so don't slice on "A.3"/"A.4" directly).
payload = txt.split("no PADDING frames:", 1)[1].split("The header", 1)[0]
header = txt.split("packet number of 1:", 1)[1].split("As a result", 1)[0]
protected = txt.split("The final protected packet is then:", 1)[1].split("A.4", 1)[0]
hx = lambda s: bytes.fromhex(re.sub(r'[^0-9a-f]', '', s))
a3_payload, a3_header, a3_protected = hx(payload), hx(header), hx(protected)
assert a3_header.hex() == "c1000000010008f067a5502a4262b50040750001", a3_header.hex()
assert len(a3_protected) == len(a3_header) + len(a3_payload) + 16

print(emit("quic_a3_header", a3_header))
print(f"quic_a3_header_len equ {len(a3_header)}")
print(f"quic_a3_pn_len equ 2")
print()
print(emit("quic_a3_payload", a3_payload))
print(f"quic_a3_payload_len equ {len(a3_payload)}")
print()
print(emit("quic_a3_protected", a3_protected))
print(f"quic_a3_protected_len equ {len(a3_protected)}")
